name: HW2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - GDAL==3.2.3-cp38-cp38-win_amd64.whl
  - Fiona==1.8.19‑cp38‑cp38‑win_amd64.whl
  - geopandas
  - contextily
  - rasterio
  - scipy
  - cartopy
  - xarray
  - openblas==0.2.19
  - netcdf4==1.5.1
  - seaborn