name: HW2_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy-base==1.23.3-py310h375b286_0
  - numpy
  - matplotlib
  - pandas
  - Fiona==1.8.19
  - geopandas
  - contextily
  - rasterio
  - scipy
  - cartopy
  - xarray
  - openblas==0.2.19
  - netcdf4==1.5.1
  - seaborn